# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(241918)
$foreground = rgb(FFF5B7)
$color0 = rgb(4C403E)
$color1 = rgb(562601)
$color2 = rgb(572701)
$color3 = rgb(834F01)
$color4 = rgb(A97501)
$color5 = rgb(A97501)
$color6 = rgb(BFAA24)
$color7 = rgb(F7E98F)
$color8 = rgb(ADA364)
$color9 = rgb(723301)
$color10 = rgb(733401)
$color11 = rgb(AE6902)
$color12 = rgb(E19C01)
$color13 = rgb(E19C01)
$color14 = rgb(FFE330)
$color15 = rgb(F7E98F)
