# /* ---- 💫 https://github.com/LinuxBeginnings 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(1E1E1F)
$foreground = rgb(F6F1E4)
$color0 = rgb(444545)
$color1 = rgb(657064)
$color2 = rgb(A95C14)
$color3 = rgb(8D696B)
$color4 = rgb(807318)
$color5 = rgb(717769)
$color6 = rgb(ABA285)
$color7 = rgb(E9E3D0)
$color8 = rgb(A39F91)
$color9 = rgb(869586)
$color10 = rgb(E27B1A)
$color11 = rgb(BC8C8F)
$color12 = rgb(AA9A20)
$color13 = rgb(979F8C)
$color14 = rgb(E4D8B1)
$color15 = rgb(E9E3D0)
